ignore:
  files:
    - "docs/*"
    - "**/test/*"
    - "**/testdata/*"
    - "**/testfiles/*"

rules:
  idiomatic:
    directory-package-mismatch:
      exclude-test-suffix: true
      ignore:
        files:
          - "docs"
          - "internal/wasm/sdk/examples/*"
          - "v1/config/*.rego"
          - "internal/configpolicy/*.rego"
          - "internal/metricsexport/*.rego"
          - "v1/plugins/server/metrics/*.rego"
          - "v1/plugins/server/encoding/*.rego"
          - "v1/plugins/server/decoding/*.rego"
  style:
    line-length:
      ignore:
        files:
          - "docs"

project:
  roots:
    - build/policy
