linter-settings:
  lll:
    line-length: 200

  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
#    - golint # deprecated and no longer supported
    - revive # replacement for golint
    - goconst
    - gofmt
    - goimports
    - unused
    - varcheck
    - deadcode
    - misspell
    - typecheck
    - structcheck
    - staticcheck
    - gosimple
    # - gosec # too many false positives
