# Copyright 2019 The OPA Authors.  All rights reserved.
# Use of this source code is governed by an Apache2
# license that can be found in the LICENSE file.

ARG GOVERSION

FROM golang:${GOVERSION}

ARG GOARCH=amd64
WORKDIR /go/src/github.com/open-policy-agent/opa

COPY . .

RUN apt-get update \
	&& apt-get install -y clang \
	&& go get -u github.com/dvyukov/go-fuzz/go-fuzz github.com/dvyukov/go-fuzz/go-fuzz-build \
	&& go-fuzz-build -libfuzzer -o ast-fuzzer.a ./ast/ \
    && clang -fsanitize=fuzzer ast-fuzzer.a -o ast-fuzzer \
    && wget -q -O fuzzit https://github.com/fuzzitdev/fuzzit/releases/download/v2.4.29/fuzzit_Linux_x86_64 \
	&& chmod a+x fuzzit