FROM golang:GOVERSION

RUN apt-get update -y \
    && apt-get install -y -q --no-install-recommends \
        ruby \
        ruby-dev \
        nodejs \
        locales \
    && gem update --system \
    && gem install jekyll \
        autoprefixer-rails \
        jekyll-assets \
        jekyll-contentblocks \
        jekyll-minifier \
    && rm -fr /var/lib/apt/lists/* /var/cache/*

RUN echo en_US.UTF-8 UTF-8 > /etc/locale.gen && locale-gen
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
