# Copyright 2019 The OPA Authors.  All rights reserved.
# Use of this source code is governed by an Apache2
# license that can be found in the LICENSE file.

# global ARG vars, see https://github.com/moby/moby/issues/37345
ARG GOVERSION

FROM golang:${GOVERSION}
ARG GOARCH=amd64
WORKDIR /go/src/github.com/open-policy-agent/opa
COPY . .
RUN make deps build-linux build-darwin build-windows
RUN mkdir /out && cp opa_linux_${GOARCH} opa_darwin_${GOARCH} opa_windows_${GOARCH}.exe /out
# Generate the test tarball from the asset files.
RUN go run test/wasm/cmd/testgen.go \
   --input-dir test/wasm/assets \
   --output /out/_test/testcases.tar.gz
