# Copyright 2019 The OPA Authors.  All rights reserved.
# Use of this source code is governed by an Apache2
# license that can be found in the LICENSE file.

ARG GOVERSION

FROM golang:${GOVERSION}

RUN apt-get update \
	&& apt-get install -y clang

RUN go get -u github.com/dvyukov/go-fuzz/go-fuzz github.com/dvyukov/go-fuzz/go-fuzz-build

RUN wget -q -O fuzzit https://github.com/fuzzitdev/fuzzit/releases/download/v2.4.77/fuzzit_Linux_x86_64
RUN chmod a+x fuzzit
RUN mv fuzzit /bin/
