name: Build (Linux/Windows)
description: release build steps
inputs:
  telemetry_url:
    description: URL of telemetry service
    required: true
runs:
  using: composite
  steps:
      - name: Download generated artifacts
        uses: actions/download-artifact@v3
        with:
          name: generated

      - id: go_version
        name: Read go version
        run: echo "go_version=$(cat .go-version)" >> $GITHUB_OUTPUT

      - name: Install Go (${{ steps.go_version.outputs.go_version }})
        uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.go_version.outputs.go_version }}

      - name: Build Darwin
        run: make ci-build-darwin ci-build-darwin-arm64-static
        timeout-minutes: 30
        env:
          TELEMETRY_URL: ${{ inputs.telemetry_url }}

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: binaries
          path: _release
