// Copyright 2026 The OPA Authors.  All rights reserved.
// Use of this source code is governed by an Apache2
// license that can be found in the LICENSE file.

package ast

import (
	"encoding/json"
	"fmt"
	"testing"

	"github.com/google/go-cmp/cmp"

	astJSON "github.com/open-policy-agent/opa/v1/ast/json"
	"github.com/open-policy-agent/opa/v1/test/conformance"
	"github.com/open-policy-agent/opa/v1/test/parsercases"
)

// TestParseCases runs the parser conformance corpus in v1/test/parsercases.
//
// A committed want_ast is regenerated by the code it tests, so it is a golden
// file: it does not independently validate OPA, it catches unreviewed change.
// The gate is review of the regeneration diff, and this test failing when
// someone edits the parser without running `make generate`.
func TestParseCases(t *testing.T) {
	defer astJSON.SetOptions(astJSON.GetOptions())

	for _, dir := range []string{"v0", "v1"} {
		set := parsercases.MustLoad("../test/parsercases/testdata/" + dir).Sorted()

		// The marshalling options are global state, so the corpus is partitioned
		// on Locations and the options are set once per group rather than per
		// case. t.Run does not return until the parallel cases it started have
		// finished, so the next group cannot change the options underneath them.
		for _, locations := range []bool{false, true} {
			group := make([]parsercases.TestCase, 0, len(set.Cases))
			for _, tc := range set.Cases {
				if tc.Locations == locations {
					group = append(group, tc)
				}
			}
			if len(group) == 0 {
				continue
			}

			astJSON.SetOptions(conformance.MarshalOptions(locations, false))
			t.Run(fmt.Sprintf("%s/locations=%t", dir, locations), func(t *testing.T) {
				for _, tc := range group {
					t.Run(tc.Note, func(t *testing.T) {
						t.Parallel()
						runParseCase(t, tc)
					})
				}
			})
		}
	}
}

func runParseCase(t *testing.T, tc parsercases.TestCase) {
	t.Helper()

	popts, err := parseCaseOptions(tc)
	if err != nil {
		t.Fatalf("%s: %v", tc.Filename, err)
	}

	module, err := ParseModuleWithOpts(parsercases.DefaultModuleName, tc.Module, popts)

	if tc.Failure() {
		if err == nil {
			t.Fatalf("%s: expected parsing to fail, but it succeeded", tc.Filename)
		}
		assertCaseErrors(t, tc.Filename, tc.WantErrors, parseCaseErrors(err), tc.Exhaustive)
		return
	}

	if err != nil {
		t.Fatalf("%s: unexpected parse error: %v", tc.Filename, err)
	}

	assertWantAST(t, tc, "module", module)

	if tc.WantEquivalent == "" {
		return
	}

	equivalent, err := ParseModuleWithOpts(parsercases.DefaultModuleName, tc.WantEquivalent, popts)
	if err != nil {
		t.Fatalf("%s: unexpected parse error in 'want_equivalent': %v", tc.Filename, err)
	}

	assertWantAST(t, tc, "want_equivalent", equivalent)
}

func assertWantAST(t *testing.T, tc parsercases.TestCase, what string, module *Module) {
	t.Helper()

	// Dropped for the same reason locations are off by default, and matching what
	// the generator writes. See MarshalAST in build/generate-parser-cases.
	module.Comments = nil

	bs, err := json.Marshal(module)
	if err != nil {
		t.Fatalf("%s: marshal %s: %v", tc.Filename, what, err)
	}

	got, err := conformance.FormatAST(bs)
	if err != nil {
		t.Fatalf("%s: format %s: %v", tc.Filename, what, err)
	}

	if got == tc.WantAST {
		return
	}

	t.Fatalf("%s: %s does not match 'want_ast' (-want, +got):\n%s\nrun `make generate` to update the corpus",
		tc.Filename, what, cmp.Diff(tc.WantAST, got))
}

func parseCaseOptions(tc parsercases.TestCase) (ParserOptions, error) {
	regoVersion, err := caseRegoVersion(tc.RegoVersion)
	if err != nil {
		return ParserOptions{}, err
	}

	popts := ParserOptions{
		RegoVersion:       regoVersion,
		Capabilities:      CapabilitiesForThisVersion(CapabilitiesExperimentalKeywords(tc.ExperimentalKeywords)),
		ProcessAnnotation: tc.Annotations,
		FutureKeywords:    tc.FutureKeywords,
		AllFutureKeywords: tc.AllFutureKeywords,
	}

	return popts, nil
}

func parseCaseErrors(err error) []conformance.Error {
	errs, ok := err.(Errors)
	if !ok {
		return []conformance.Error{{Message: err.Error()}}
	}

	got := make([]conformance.Error, 0, len(errs))
	for _, e := range errs {
		got = append(got, caseError(e))
	}
	return got
}
