all:
ifndef VERSION
$(error VERSION is not set)
endif
	rm -fr public resources generated
	echo "- $(VERSION)" > data/releases.yaml
	mkdir -p generated/docs
	cp -r content/docs generated/docs/v$(VERSION)
	hugo \
		--contentDir generated \
		--ignoreCache \
		--minify
	tar czvf site.tar.gz -C public .