name: Run Benchmarks

on:
  workflow_call:
    inputs:
      publish:
        description: Whether to publish benchmark results
        required: true
        type: boolean
      publish_branch:
        description: Branch to publish results to
        required: false
        type: string
        default: ''

jobs:
  benchmarks:
    name: Benchmarks
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: opa
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: opa/.go-version
          cache-dependency-path: opa/go.sum
      - name: Run benchmarks
        run: go run go.bobheadxi.dev/gobenchdata@v1 action
        env:
          INPUT_GO_TEST_FLAGS: "-tags=opa_wasm -timeout=120m -run=^#"
          INPUT_GO_TEST_PKGS: ./...
          INPUT_SUBDIRECTORY: opa
          INPUT_PUBLISH: ${{ inputs.publish }}
          INPUT_PUBLISH_BRANCH: ${{ inputs.publish_branch }}
          INPUT_PRUNE_COUNT: 250
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 120
