name: Test Docs

on:
  pull_request:
    paths:
      - 'docs/**'

# When a new revision is pushed to a PR, cancel all in-progress CI runs for that
# PR. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-docs:
    name: Test Docs
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Download OPA
        uses: open-policy-agent/setup-opa@34a30e8a924d1b03ce2cf7abe97250bbb1f332b5 # v2.2.0
        with:
          version: edge

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3.0.0
        with:
          # keep this version in sync with the version in netlify.toml
          # Note, that upgrading Hugo is tricky as all versions of the OPA docs need to work
          # with the Hugo version used.
          # see: https://github.com/open-policy-agent/opa/pull/7034
          hugo-version: "0.113.0"
          extended: true

      - name: Build docs site and test integrations data
        run: |
          cd docs
          make dev-generate hugo-production-build
          cd -
          opa eval --v0-compatible 'data.integrations.deny[message]' -i docs/website/public/index.json -d build/policy/integrations.rego --format=values --fail-defined
