name: OPA

on:
  pull_request:
    branch: *
  push:
    branch: master

jobs:
  # Golang build and tests workflow.
  # Note: The build uses Docker so do *not* setup Golang on the runner vm.
  # TODO: Split into separate build, test, perf, and check targets to lower overall runtime of PR checks.
  go:
    name: Go Build and Test
    runs-on: ubuntu-18.04
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Build and Test Golang
      run: make travis-go

  # WebAssembly build and tests workflow, can run independent of other workflows.
  wasm:
    name: WASM Build and Test
    runs-on: ubuntu-18.04
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build and Test WASM
      run: make travis-wasm

  deploy-edge:
    name: Deploy Edge
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    needs: [go, wasm]
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Deploy OPA Edge
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # TODO: Remove s3 bucket override
        #run: make deploy-travis
        run: make deploy-travis OPA_S3_RELEASE_BUCKET=test-opa-releases IMAGE_ORG=patrickeast
